<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rendering" nsURI="org.sheepy.lily.vulkan.extra.model.rendering"
    nsPrefix="rendering">
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true" interface="true"
      eSuperTypes="../../org.sheepy.lily.core.model/model/types.ecore#//LNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalEntity" abstract="true" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geoLocation" eType="ecore:EDataType ../../org.sheepy.lily.core.model/model/types.ecore#//Vector3d"
        defaultValueLiteral="0;0;0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geoOrientation" eType="ecore:EDataType ../../org.sheepy.lily.core.model/model/types.ecore#//Vector2f"
        defaultValueLiteral="0;0;0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="axisLocation" eType="ecore:EDataType ../../org.sheepy.lily.core.model/model/types.ecore#//Vector3d"
        defaultValueLiteral="0;0;0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axis" eType="#//Axis" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Axis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frontDirection" eType="ecore:EDataType ../../org.sheepy.lily.core.model/model/types.ecore#//Vector3d"
        defaultValueLiteral="0;0;0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upDirection" eType="ecore:EDataType ../../org.sheepy.lily.core.model/model/types.ecore#//Vector3d"
        defaultValueLiteral="0;0;0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rightDirection" eType="ecore:EDataType ../../org.sheepy.lily.core.model/model/types.ecore#//Vector3d"
        defaultValueLiteral="0;0;0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Presentation" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentedEntities" upperBound="-1"
        eType="#//PresentableEntity" eOpposite="#//PresentableEntity/presentation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationPkg" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Presentation"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentations" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//PresentationPkg/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentableEntity" eSuperTypes="#//PhysicalEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentation" eType="#//Presentation"
        eOpposite="#//Presentation/presentedEntities"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericRenderer" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Presentation"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataProviderPkg" lowerBound="1"
        containment="true">
      <eGenericType eClassifier="#//DataProviderPkg">
        <eTypeArguments eTypeParameter="#//GenericRenderer/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationPkg" lowerBound="1">
      <eGenericType eClassifier="#//PresentationPkg">
        <eTypeArguments>
          <eUpperBound eTypeParameter="#//GenericRenderer/T"/>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constantBuffer" eType="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/resource.ecore#//ConstantBuffer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pushBuffer" lowerBound="1"
        eType="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/resource.ecore#//PushBuffer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commonResourceProvider"
        eType="#//ResourceProvider" containment="true"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/graphic.ecore#//GraphicsPipeline"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.sheepy.lily.core.model/model/maintainer.ecore#//Maintainer">
      <eTypeArguments eClassifier="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/graphic.ecore#//GraphicsPipeline"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericDataProvider" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Presentation"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/resource.ecore#//BufferDataProvider">
      <eTypeArguments eClassifier="#//RenderableDataSource">
        <eTypeArguments eTypeParameter="#//GenericDataProvider/T"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataProviderPkg">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Presentation"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataProviders" lowerBound="1"
        upperBound="-1" containment="true">
      <eGenericType eClassifier="#//GenericDataProvider">
        <eTypeArguments eTypeParameter="#//DataProviderPkg/T"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericDescribedDataProvider">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Presentation"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//GenericDataProvider">
      <eTypeArguments eTypeParameter="#//GenericDescribedDataProvider/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/resource.ecore#//DescribedDataProvider">
      <eTypeArguments eClassifier="#//RenderableDataSource">
        <eTypeArguments eTypeParameter="#//GenericDescribedDataProvider/T"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RenderableDataSource">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Presentation"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentation" lowerBound="1">
      <eGenericType eTypeParameter="#//RenderableDataSource/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="part" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericVertexProvider">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Presentation"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//GenericDataProvider">
      <eTypeArguments eTypeParameter="#//GenericVertexProvider/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericIndexProvider">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Presentation"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexType" lowerBound="1"
        eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EIndexType"
        defaultValueLiteral="UINT32"/>
    <eGenericSuperTypes eClassifier="#//GenericDataProvider">
      <eTypeArguments eTypeParameter="#//GenericIndexProvider/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationRootPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationPkgs" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//PresentationPkg">
        <eTypeArguments>
          <eUpperBound eClassifier="#//Presentation"/>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceProvider" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StaticResourceProvider" eSuperTypes="#//ResourceProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/resource.ecore#//DescriptedResource"/>
  </eClassifiers>
</ecore:EPackage>
