<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sprite" nsURI="org.sheepy.lily.vulkan.extra.model.sprite" nsPrefix="sprite">
  <eClassifiers xsi:type="ecore:EClass" name="SpriteExtension" eSuperTypes="../../org.sheepy.lily.vulkan.model/model/process.ecore#//IPipelineExtension ../../org.sheepy.lily.vulkan.model/model/vulkanresource.ecore#//IBufferDataSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="drawTask" lowerBound="1"
        eType="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/graphic.ecore#//DrawIndexed"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexBufferViewer" lowerBound="1"
        eType="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/vulkanresource.ecore#//BufferViewer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertexBufferViewer" lowerBound="1"
        eType="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/vulkanresource.ecore#//BufferViewer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spritesDescriptor" lowerBound="1"
        eType="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/vulkanresource.ecore#//ImageDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spriteDataSource" lowerBound="1"
        eType="#//ISpriteDataSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spritePipelineSpecialization"
        eType="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/vulkanresource.ecore#//ConstantBuffer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spriteImageMemory" lowerBound="1"
        eType="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/vulkanresource.ecore#//MemoryChunk"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISpriteDataSource" abstract="true" interface="true"
      eSuperTypes="../../org.sheepy.lily.vulkan.model/model/vulkanresource.ecore#//IBufferDataSource"/>
</ecore:EPackage>
