<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="process" nsURI="org.sheepy.lily.vulkan.model.process" nsPrefix="process">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractProcess" abstract="true" eSuperTypes="vulkan.ecore#//IProcess">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingFenceDuringAcquire"
        unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyDescription" value="If fenceEnabled, will wait during acquire. Useless for a render process that already wait for image acquiring"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partPkg" eType="#//ProcessPartPkg"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resetAllowed" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" upperBound="-1"
        eType="ecore:EClass resource.ecore#//Semaphore">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Semaphores"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="waitFor" upperBound="-1"
        eType="ecore:EClass resource.ecore#//Semaphore">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Semaphores"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessPartPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//IProcessPart" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPipelineTask" abstract="true" interface="true"
      eSuperTypes="../../org.sheepy.lily.core.model/model/types.ecore#//LNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IProcessPart" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IPipeline" abstract="true" interface="true"
      eSuperTypes="../../org.sheepy.lily.core.model/model/types.ecore#//LNamedElement vulkan.ecore#//IResourceContainer #//IProcessPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stage" unique="false" eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//ECommandStage"
        defaultValueLiteral="Render"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pushConstantRanges" upperBound="-1"
        eType="ecore:EClass ../../org.sheepy.vulkan.model/model/pipeline.ecore#//PushConstantRange"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specializationData" unique="false"
        eType="ecore:EDataType resource.ecore#//ByteBuffer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptorSetPkg" eType="ecore:EClass resource.ecore#//DescriptorSetPkg"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskPkg" eType="#//TaskPkg"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//IPipelineTask" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline" eSuperTypes="#//IPipeline"/>
  <eClassifiers xsi:type="ecore:EClass" name="PipelineBarrier" eSuperTypes="../../org.sheepy.lily.core.model/model/root.ecore#//LObject #//IPipelineTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="barriers" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.sheepy.vulkan.model/model/barrier.ecore#//Barrier"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="srcStage" unique="false"
        eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EPipelineStage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dstStage" unique="false"
        eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EPipelineStage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srcQueue" eType="#//AbstractProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dstQueue" eType="#//AbstractProcess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeatCount" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//IPipelineTask" containment="true" resolveProxies="false"/>
    <eGenericSuperTypes eClassifier="#//IPipelineTask"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.sheepy.lily.core.model/model/maintainer.ecore#//Maintainable">
      <eTypeArguments eClassifier="#//CompositeTask"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BindDescriptorSets" eSuperTypes="#//IPipelineTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptorSets" upperBound="-1"
        eType="ecore:EClass resource.ecore#//DescriptorSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindPoint" lowerBound="1"
        eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EBindPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PushConstant" abstract="true" eSuperTypes="#//IPipelineTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stages" lowerBound="1"
        upperBound="-1" eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EShaderStage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PushConstantBuffer" eSuperTypes="#//PushConstant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buffer" lowerBound="1"
        eType="ecore:EClass resource.ecore#//ConstantBuffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PushBufferTask" eSuperTypes="#//IPipelineTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pushBuffer" lowerBound="1"
        eType="ecore:EClass resource.ecore#//PushBuffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetBufferTask" eSuperTypes="#//IPipelineTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="getBuffer" lowerBound="1"
        eType="ecore:EClass resource.ecore#//GetBuffer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceBuffer" eType="ecore:EClass resource.ecore#//Buffer"/>
  </eClassifiers>
</ecore:EPackage>
