<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="resource" nsURI="org.sheepy.lily.vulkan.model.resource" nsPrefix="resource">
  <eClassifiers xsi:type="ecore:EClass" name="TransferBuffer" eSuperTypes="../../org.sheepy.lily.core.model/model/application.ecore#//IResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceCount" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedToPush" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedToFetch" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantBuffer" eSuperTypes="../../org.sheepy.lily.core.model/model/application.ecore#//IResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" unique="false" eType="#//ByteBuffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBuffer" abstract="true" interface="true"
      eSuperTypes="../../org.sheepy.lily.core.model/model/application.ecore#//IResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Buffer" eSuperTypes="#//IBuffer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usages" upperBound="-1"
        eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EBufferUsage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" unique="false" eType="#//ByteBuffer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keptMapped" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostVisible" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceCount" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyDescription" value="Every push in this buffer will write on the next instance, and update the descriptor acordingly"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coherent" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeBuffer" eSuperTypes="#//IBuffer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataProviders" upperBound="-1"
        containment="true" resolveProxies="false">
      <eGenericType eClassifier="#//BufferDataProvider">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transferBuffer" lowerBound="1"
        eType="#//TransferBuffer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EFlushMode">
    <eLiterals name="PUSH"/>
    <eLiterals name="FETCH" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositePartReference" eSuperTypes="../../org.sheepy.lily.core.model/model/types.ecore#//LNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="part" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBufferReference" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BufferReference" eSuperTypes="#//IBufferReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buffer" lowerBound="1"
        eType="#//Buffer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeBufferReference" eSuperTypes="#//CompositePartReference #//IBufferReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buffer" lowerBound="1"
        eType="#//CompositeBuffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BufferDataProvider" eSuperTypes="../../org.sheepy.lily.core.model/model/types.ecore#//LNamedElement">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usage" unique="false" lowerBound="1"
        eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EBufferUsage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceCount" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="property" value="Readonly"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//BufferDataProvider/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedToPush" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedToFetch" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stageBeforePush" eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EPipelineStage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessBeforePush" upperBound="-1"
        eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EAccess"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stageBeforeFetch" eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EPipelineStage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessBeforeFetch" upperBound="-1"
        eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EAccess"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="growFactor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="growThreshold" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ByteBuffer" instanceClassName="java.nio.ByteBuffer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Image" abstract="true" eSuperTypes="../../org.sheepy.lily.core.model/model/application.ecore#//IResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialLayout" eType="ecore:EClass ../../org.sheepy.vulkan.model/model/Image.ecore#//ImageLayout"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticImage" eSuperTypes="#//Image ../../org.sheepy.vulkan.model/model/Image.ecore#//ImageInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillWithZero" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillWith" eType="#//ByteBuffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileImage" eSuperTypes="#//Image">
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" eType="ecore:EClass ../../org.sheepy.lily.core.model/model/application.ecore#//FileResource"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mipmapEnabled" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SampledImage" eSuperTypes="../../org.sheepy.lily.core.model/model/application.ecore#//IResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sampler" lowerBound="1"
        eType="ecore:EClass ../../org.sheepy.vulkan.model/model/Image.ecore#//SamplerInfo"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" lowerBound="1" eType="#//Image"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sampler" eSuperTypes="../../org.sheepy.vulkan.model/model/Image.ecore#//SamplerInfo ../../org.sheepy.lily.core.model/model/application.ecore#//IResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//Image"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semaphore" eSuperTypes="../../org.sheepy.lily.core.model/model/application.ecore#//IResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signalizedAtInit" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitStage" unique="false"
        eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EPipelineStage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FontImage" eSuperTypes="#//Image">
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" eType="ecore:EClass ../../org.sheepy.lily.core.model/model/application.ecore#//FileResource"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="18"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BufferDescriptor" eSuperTypes="vulkan.ecore#//IDescriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bufferReference" lowerBound="1"
        eType="#//IBufferReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageDescriptor" eSuperTypes="vulkan.ecore#//IDescriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" lowerBound="1" eType="#//Image"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SampledImageDescriptor" eSuperTypes="vulkan.ecore#//IDescriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sampledImage" eType="#//SampledImage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SamplerDescriptor" eSuperTypes="vulkan.ecore#//IDescriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sampler" lowerBound="1"
        eType="#//Sampler"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Texture2DArrayDescriptor" eSuperTypes="vulkan.ecore#//IDescriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="texture2DArray" lowerBound="1"
        eType="#//Texture2DArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptorSet" eSuperTypes="../../org.sheepy.lily.core.model/model/types.ecore#//LNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptors" lowerBound="1"
        upperBound="-1" eType="ecore:EClass vulkan.ecore#//IDescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptorSetPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptorSets" upperBound="-1"
        eType="#//DescriptorSet" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BufferBarrier" eSuperTypes="../../org.sheepy.vulkan.model/model/barrier.ecore#//AbstractBufferBarrier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buffer" eType="#//Buffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeBufferBarrier" eSuperTypes="../../org.sheepy.vulkan.model/model/barrier.ecore#//AbstractBufferBarrier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataProvider" lowerBound="1">
      <eGenericType eClassifier="#//BufferDataProvider">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageBarrier" eSuperTypes="../../org.sheepy.vulkan.model/model/barrier.ecore#//AbstractImageBarrier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" lowerBound="1" eType="#//Image"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shader" eSuperTypes="../../org.sheepy.lily.core.model/model/application.ecore#//IResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" eType="ecore:EClass ../../org.sheepy.lily.core.model/model/application.ecore#//FileResource"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stage" unique="false" eType="ecore:EEnum ../../org.sheepy.vulkan.model/model/enumeration.ecore#//EShaderStage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="ecore:EClass ../../org.sheepy.vulkan.model/model/pipeline.ecore#//SpecializationConstant"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Texture2DArray" eSuperTypes="../../org.sheepy.lily.core.model/model/application.ecore#//IResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" lowerBound="1" upperBound="-1"
        eType="ecore:EClass ../../org.sheepy.lily.core.model/model/application.ecore#//FileResource"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mipmapEnabled" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialLayout" eType="ecore:EClass ../../org.sheepy.vulkan.model/model/Image.ecore#//ImageLayout"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
